### ISSUE TITLE
flight finder using outdated _all query

### ISSUE THREAD

**Issue by rsmith013** [cedadev/ceda-map-uis#64]
This does not work agains es7. Probably need to switch to query string

**Comment by spepler** [comment]
replace 
         {term: {  _all: ft[i].toLowerCase()}}

with 
     {"simple_query_string" : {"query": ft }}

**Comment by spepler** [comment]
should be assigned to Daniel but can't find in github?

**Comment by dwest77a** [comment]
with
{"simple_query_string" : {"query": ft }}
I get an error in response json

{
   "error":{
      "root_cause":[
         {
            "type":"parsing_exception",
            "reason":"[
               simple_query_string]
             query does not support [
               query]
            ",  ...

I think the original _all part does work i.e doesn't produce an error. It just produces 0 hits. Will investigate

**Comment by dwest77a** [comment]
Correctly functions now using "query_string", not "simple_query_string". Search by flight number still not working though but I'm looking into things

**Comment by dwest77a** [comment]
query_string seems to only work using string entries - numbers as part of strings are ignored?
I've replaced the geographical search with a flight number search in my branch, and relabelled logos etc. with CEDA instead of EUFAR. Will look at flight info next to see if further text-based info can be displayed to assist with keyword search.

**Comment by dwest77a** [comment]
Fixed in flights-ui - elasticsearch query is properly formatted to es7
